        pipeline {
    agent {
        dockerfile {
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    
    stages {
	    
        stage('build') {
            steps {
               git url: 'https://github.com/jagathkriish/Java_Devops.git'
                sh "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
                   -Dsonar.host.url=https://sonarcloud.io \
                   -Dsonar.organization=jagathkriish-github \
                   -Dsonar.login=bd19ceec380b12479adf538eb09602629750e7a4"
                sh "cd target && ls -al"
            }
        }
    }
}
